# Generated by Django 2.2.3 on 2019-07-15 12:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nightmare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NightmarePart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='nightmare_part/')),
                ('text', markdownx.models.MarkdownxField()),
                ('nightmare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightmareparts', to='nightmare.Nightmare')),
            ],
        ),
        migrations.CreateModel(
            name='NightmareSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nightmarsurvey', to='nightmare.NightmarePart')),
            ],
        ),
        migrations.CreateModel(
            name='NightmareSurveyProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nightmaresurveypropositions', to='nightmare.NightmareSurvey')),
                ('votes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
