# Generated by Django 2.2.3 on 2019-07-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightmare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightmaresurveyproposition',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
