# Generated by Django 2.2.3 on 2019-07-15 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nightmare', '0002_auto_20190715_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightmaresurveyproposition',
            name='votes',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
