# Generated by Django 2.1.3 on 2018-11-29 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nightmare', '0006_auto_20181129_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightmarepart',
            name='survey',
        ),
        migrations.AlterField(
            model_name='nightmare',
            name='date_creation',
            field=models.DateField(default=datetime.datetime(2018, 11, 29, 19, 52, 12, 995392, tzinfo=utc)),
        ),
    ]
