# Generated by Django 2.1.3 on 2018-11-29 23:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nightmare', '0007_auto_20181129_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nightmare',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 29, 23, 16, 45, 423991, tzinfo=utc)),
        ),
    ]
