# Generated by Django 2.1.3 on 2018-11-30 00:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nightmare', '0008_auto_20181130_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightmaresurvey',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 0, 12, 5, 922018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='nightmare',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 0, 12, 5, 921021, tzinfo=utc)),
        ),
    ]
